# These substitutions allow the end user to override certain values
substitutions:
  name: "light_relay"

esphome:
  name: "${name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: esphome.project-template
    version: "1.0"

esp8266:
  board: nodemcuv2

switch:
  - platform: gpio
    id: bulb
    pin:
      number: GPIO2
      inverted: True

logger:

# OTA is required for Over-the-Air updating
ota:

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "light_relay"

captive_portal:
